INSERT INTO authorities (authority) VALUES ('user');
INSERT INTO authorities (authority) VALUES ('admin');
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo@correo.es', 'Antonio', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'admin', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo@correo.com', 'User1', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario1', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo1@correo.com', 'User2', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario2', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo2@correo.com', 'User3', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario3', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo3@correo.com', 'User4', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario4', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo4@correo.com', 'User5', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario5', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo5@correo.com', 'User6', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario6', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo6@correo.com', 'User7', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario7', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo7@correo.com', 'User8', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario8', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo8@correo.com', 'User9', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario9', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo9@correo.com', 'User0', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario0', true, true, 0);
INSERT INTO users (email, name, password, username, enabled, not_locker, quotes) VALUES ('correo0@correo.com', 'User10', '$2y$12$pgO2JRJ8n1Q8Cw1sviyo/eQ9isg1zBGUyh3swEmMKEIXx3JUeOKpy', 'usuario10', true, true, 0);
insert into users_authorities (authority_id, user_id) values (1,1);
insert into users_authorities (authority_id, user_id) values (2,1);
insert into users_authorities (authority_id, user_id) values (1,2);
insert into users_authorities (authority_id, user_id) values (1,3);
insert into users_authorities (authority_id, user_id) values (1,4);
insert into users_authorities (authority_id, user_id) values (1,5);
insert into users_authorities (authority_id, user_id) values (1,6);
insert into users_authorities (authority_id, user_id) values (1,7);
insert into users_authorities (authority_id, user_id) values (1,8);
insert into users_authorities (authority_id, user_id) values (1,9);
insert into users_authorities (authority_id, user_id) values (1,10);
insert into users_authorities (authority_id, user_id) values (1,11);
insert into users_authorities (authority_id, user_id) values (1,12);
insert into publications (date_of_send, publication, publicationtransform, view, user_id) values ('2020-03-26 13:22:06.294000', 'esto es una publicacion para que esto tenga algo', 'esto es una publicacion para que esto tenga algo', 1, 1);
insert into publications (date_of_send, publication, publicationtransform, view, user_id) values ('2020-03-28 13:22:06.294000', 'esto es una otra publi para que esto tenga algo', 'esto es una otra publi para que esto tenga algo', 1, 2);
insert into publications (date_of_send, publication, publicationtransform, view, user_id) values ('2020-03-21 13:22:06.294000', 'esto es unmensaje que no se ve', 'esto es unmensaje que no se ve', 0, 2);
insert into follows (user_id, followed_id) values (1, 1);
insert into follows (user_id, followed_id) values (1, 2);
insert into follows (user_id, followed_id) values (2, 1);
insert into follows (user_id, followed_id) values (2, 2);
